shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('product-specifications/', include('specifications.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/specifications/urls.py
from django.urls import path

from .views import (
    BaseSpecView,
    CreateNewCharacteristic,
    CreateNewCategory,
    CreateNewCharacteristicValidator,
    CharacteristicChoiceView,
    CreateCharacteristicView,
    NewProductCharacteristicView,
    SearchProductAjaxView,
    AttachNewCharacteristicToProduct,
    ProductCharacteristicChoicesAjaxView,
    CreateNewProductCharacteristicAjaxView,
    UpdateProductCharacteristicsView,
    ShowProductCharacteristicsForUpdate,
    UpdateProductCharacteristicsAjaxView,

)

urlpatterns = [
    path('', BaseSpecView.as_view(), name='product-list-for-characteristics'),
    path('new-characteristic/', CreateNewCharacteristic.as_view(), name='new-characteristic'),
    path('new-category/', CreateNewCategory.as_view(), name='new-category'),
    path('new-validator/', CreateNewCharacteristicValidator.as_view(), name='new-validator'),
    path('characteristic-choice/', CharacteristicChoiceView.as_view(), name='characteristic-choice-validators'),
    path('characteristic-create/', CreateCharacteristicView.as_view(), name='create-characteristic'),
    path('new-product-characteristic/', NewProductCharacteristicView.as_view(), name='new-product-characteristic'),
    path('search-product/', SearchProductAjaxView.as_view(), name='search-product'),
    path('attach-characteristic/', AttachNewCharacteristicToProduct.as_view(), name='attach-characteristic'),
    path('product-characteristic/', ProductCharacteristicChoicesAjaxView.as_view(), name='product-characteristic'),
    path('attach-new-product-characteristic/', CreateNewProductCharacteristicAjaxView.as_view(), name='attach-new-product-characteristic'),
    path('update-product-characteristics/', UpdateProductCharacteristicsView.as_view(), name='update-product-characteristics'),
    path('show-product-characteristics-for-update/', ShowProductCharacteristicsForUpdate.as_view(), name='show-product-characteristics-for-update'),
    path('update-product-characteristics-ajax/', UpdateProductCharacteristicsAjaxView.as_view(), name='update-product-characteristics-ajax')

]

shop/specifications/models.py
from django.db import models


class CategoryCharacteristic(models.Model):

    category = models.ForeignKey("mainapp.Category", verbose_name='Категория', on_delete=models.CASCADE)
    characteristic_name = models.CharField(verbose_name='Название ключа для категории', max_length=50)
    characteristic_filter_name = models.CharField(verbose_name='Название для фильтра', max_length=50)
    unit = models.CharField(max_length=50, verbose_name='Единица измерения', null=True, blank=True)

    class Meta:
        unique_together = ('category', 'characteristic_name', 'characteristic_filter_name')

    def __str__(self):
        return f"{self.category.name} | {self.characteristic_name}"


class CharacteristicValidator(models.Model):

    category = models.ForeignKey("mainapp.Category", verbose_name='Категория', on_delete=models.CASCADE)
    characteristic_key = models.ForeignKey(CategoryCharacteristic, verbose_name='Ключ характеристики', on_delete=models.CASCADE)
    valid_characteristic_value = models.CharField(max_length=100, verbose_name='Значение характеристики')

    def __str__(self):
        return f"Категория {self.category.name} | " \
               f"Характристика {self.characteristic_key.characteristic_name} | " \
               f"Значение характеристики {self.valid_characteristic_value}"


class ProductCharacteristics(models.Model):

    product = models.ForeignKey("mainapp.Product", verbose_name='Товар', on_delete=models.CASCADE)
    characteristic = models.ForeignKey(CategoryCharacteristic, verbose_name='Характеристика', on_delete=models.CASCADE)
    value = models.CharField(max_length=255, verbose_name='Значение')

    def __str__(self):
        return f"Товар - {self.product.title} | " \
               f"Характеристика - {self.characteristic.characteristic_name} | " \
               f"Значение - {self.value}"

shop/specifications/forms.py
from django import forms

from mainapp.models import Category
from .models import CharacteristicValidator, CategoryCharacteristic


class NewCategoryCharacteristicKeyForm(forms.ModelForm):

    class Meta:
        model = CategoryCharacteristic
        fields = '__all__'


class NewCategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = '__all__'


class CharacteristicValidatorForm(forms.ModelForm):

    class Meta:
        model = CharacteristicValidator
        fields = ['category']

shop/specifications/views.py
from collections import defaultdict

from django.contrib import messages
from django.shortcuts import render
from django.views.generic import View
from django.http import HttpResponseRedirect, JsonResponse

from .models import CategoryCharacteristic, CharacteristicValidator, ProductCharacteristics
from .forms import NewCategoryCharacteristicKeyForm, NewCategoryForm
from mainapp.models import Category, Product


class BaseSpecView(View):

    def get(self, request, *args, **kwargs):
        return render(request, 'product_characteristics.html', {})


class CreateNewCharacteristic(View):

    def get(self, request, *args, **kwargs):
        form = NewCategoryCharacteristicKeyForm(request.POST or None)
        context = {'form': form}
        return render(request, 'new_characteristic.html', context)

    def post(self, request, *args, **kwargs):
        form = NewCategoryCharacteristicKeyForm(request.POST or None)
        if form.is_valid():
            new_category_characteristic_key = form.save(commit=False)
            new_category_characteristic_key.category = form.cleaned_data['category']
            new_category_characteristic_key.characteristic_name = form.cleaned_data['characteristic_name']
            new_category_characteristic_key.save()
        return HttpResponseRedirect('/product-specifications/')


class CreateNewCategory(View):

    def get(self, request, *args, **kwargs):
        form = NewCategoryForm(request.POST or None)
        context = {'form': form}
        return render(request, 'new_category.html', context)

    def post(self, request, *args, **kwargs):
        form = NewCategoryForm(request.POST or None)
        if form.is_valid():
            new_category = form.save(commit=False)
            new_category.name = form.cleaned_data['name']
            new_category.save()
        return HttpResponseRedirect('/product-specifications/')


class CreateNewCharacteristicValidator(View):

    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        context = {'categories': categories}
        return render(request, 'new_validator.html', context)


class CharacteristicChoiceView(View):

    def get(self, request, *args, **kwargs):
        option = '<option value="{value}">{option_name}</option>'
        html_select = """
            <select class="form-select" name="characteristic-validators" id="characteristic-validators-id" aria-label="Default select example">
                <option selected>---</option>
                {result}
            </select>
                    """
        characteristic_key_qs = CategoryCharacteristic.objects.filter(
            category_id=int(request.GET.get('category_id'))
        )
        res_string = ""
        for item in characteristic_key_qs:
            res_string += option.format(value=item.characteristic_name, option_name=item.characteristic_name)
        html_select = html_select.format(result=res_string)
        return JsonResponse({"result": html_select, "value": int(request.GET.get('category_id'))})


class CreateCharacteristicView(View):

    def get(self, request, *args, **kwargs):
        category_id = request.GET.get('category_id')
        characteristic_name = request.GET.get('characteristic_name')
        value = request.GET.get('characteristic_value').strip(" ")
        print(value)
        category = Category.objects.get(id=int(category_id))
        characteristic = CategoryCharacteristic.objects.get(category=category, characteristic_name=characteristic_name)
        existed_object, created = CharacteristicValidator.objects.get_or_create(
            category=category,
            characteristic_key=characteristic,
            valid_characteristic_value=value
        )
        if not created:
            return JsonResponse({
                "error": f"Значение '{value}' уже существует."
            })
        messages.add_message(
            request, messages.SUCCESS,
            f'Значение "{value}" для характеристики '
            f'"{characteristic.characteristic_name}" в категории {category.name} успешно создано'
        )
        return JsonResponse({'result': 'ok'})


class NewProductCharacteristicView(View):

    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        context = {'categories': categories}
        return render(request, 'new_product_characteristic.html', context)


class SearchProductAjaxView(View):

    def get(self, request, *args, **kwargs):
        query = request.GET.get('query')
        category_id = request.GET.get('category_id')
        category = Category.objects.get(id=int(category_id))
        products = list(Product.objects.filter(
            category=category,
            title__icontains=query
        ).values())
        return JsonResponse({"result": products})


class AttachNewCharacteristicToProduct(View):

    def get(self, request, *args, **kwargs):
        res_string = ""
        product = Product.objects.get(id=int(request.GET.get('product_id')))
        existing_characteristics = list(set([item.characteristic.characteristic_name for item in product.characteristics.all()]))
        print(existing_characteristics)
        category_characteristics = CategoryCharacteristic.objects.filter(
            category=product.category
        ).exclude(characteristic_name__in=existing_characteristics)
        option = '<option value="{value}">{option_name}</option>'
        html_select = """
            <select class="form-select" name="product-category-characteristics" id="product-category-characteristics-id" aria-label="Default select example">
                <option selected>---</option>
                {result}
            </select>
                    """
        for item in category_characteristics:
            res_string += option.format(value=item.category.id, option_name=item.characteristic_name)
        html_select = html_select.format(result=res_string)
        return JsonResponse({"characteristics": html_select})


class ProductCharacteristicChoicesAjaxView(View):

    def get(self, request, *args, **kwargs):
        res_string = ""
        category = Category.objects.get(id=int(request.GET.get('category_id')))
        characteristic_key = CategoryCharacteristic.objects.get(
            category=category,
            characteristic_name=request.GET.get('product_characteristic_name')
        )
        validators_qs = CharacteristicValidator.objects.filter(
            category=category,
            characteristic_key=characteristic_key
        )
        option = '<option value="{value}">{option_name}</option>'
        html_select = """
            <select class="form-select" name="product-category-characteristics-choices" id="product-category-characteristics-choices-id" aria-label="Default select example">
                <option selected>---</option>
                {result}
            </select>
                    """
        for item in validators_qs:
            res_string += option.format(value=item.id, option_name=item.valid_characteristic_value)
        html_select = html_select.format(result=res_string)
        return JsonResponse({"characteristics": html_select})


class CreateNewProductCharacteristicAjaxView(View):

    def get(self, request, *args, **kwargs):
        product = Product.objects.get(title=request.GET.get('product'))
        category_characteristic = CategoryCharacteristic.objects.get(
            category=product.category,
            characteristic_name=request.GET.get('category_characteristic')
        )
        value = request.GET.get('value')
        characteristic = ProductCharacteristics.objects.create(
            characteristic=category_characteristic,
            product=product,
            value=value
        )
        product.characteristics.add(characteristic)
        return JsonResponse({"OK": "OK"})


class UpdateProductCharacteristicsView(View):

    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        context = {'categories': categories}
        return render(request, 'update_product_characteristics.html', context)


class ShowProductCharacteristicsForUpdate(View):

    def get(self, request, *args, **kwargs):
        product = Product.objects.get(id=int(request.GET.get('product_id')))
        characteristics_values_qs = product.characteristics.all()
        head = """
        <hr>
            <div class="row">
                <div class="col-md-4">
                    <h4 class="text-center">Характеристика</h4>
                </div>
                <div class="col-md-4">
                    <h4 class="text-center">Текущее значение</h4>
                </div>
                <div class="col-md-4">
                    <h4 class="text-center">Новое значение</h4>
                </div>
            </div>
        <div class='row'>{}</div>
        <div class="row">
        <hr>
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <p class='text-center'><button class="btn btn-success" id="save-updated-characteristics">Сохранить</button></p> 
        </div>
        <div class="col-md-4">
        </div>
        </div>
        """
        option = '<option value="{value}">{option_name}</option>'
        select_values = """
            <select class="form-select" name="characteristic-value" id="characteristic-value" aria-label="Default select example">
                <option selected>---</option>
                {result}
            </select>
                    """
        mid_res = ""
        select_different_values_dict = defaultdict(list)
        for item in characteristics_values_qs:
            fv_qs = CharacteristicValidator.objects.filter(
                category=item.product.category,
                characteristic_key=item.characteristic
            ).values()
            for fv in fv_qs:
                if fv['valid_characteristic_value'] == item.value:
                    pass
                else:

shop/specifications/templates/mass_add_characteristics.html
{% extends 'product_characteristics.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="category-validator-div">
    <label for="category-validators-id">Категория</label>
    <select class="form-select" name="category-validators" id="category-validators-id" aria-label="Default select example">
    <option selected>---</option>
        {% for category in categories %}
          <option value="{{ category.id }}">{{ category.name }}</option>
        {% endfor %}
    </select>
</div>
    <div class="product-search-ajax" style="display: none; margin-top: 20px;">
      <div class="form-group">
        <label for="search-text">Поиск товара</label>
        <input type="text" name='search-text' class="form-control" id="search-text" aria-describedby="emailHelp" placeholder="Введите слова для поиска">
      </div>
    </div>
    <div class="search-results">
        <ul class="list-group" id="no-results" style="display: none">
            <li class="list-group-item list-group-item-light">По вашему запросу результатов не найдено</li>
        </ul>
        <ul class="list-group" id="search-product-results" style="padding-top: 10px;">
        </ul>
    </div>
<div class="product" style="margin-top: 30px;">
</div>
<div class="product-characteristic-choices">

</div>
<input type="submit" class="btn btn-success" value="Создать" style="display: none; margin-top: 10px;" id="create-product-characteristic">
{% endblock %}
{% block masscharacteristics %}
<div class="product-characteristics" style="margin-top: 10px;">
</div>
{% endblock masscharacteristics %}
{% block js %}
<script>
    $(document).on('click', "#create-product-characteristic", function (){
        let product = $("#product-title").text()
        let category_characteristic = $("#product-category-characteristics-id option:selected").text()
        let value = $("#product-category-characteristics-choices-id option:selected").text()
        let data = {
            product: product,
            category_characteristic: category_characteristic,
            value: value
        }
        $.ajax({
            method: "GET",
            dataType: "json",
            data: data,
            url: '/product-specifications/attach-new-product-characteristic/',
            success: function (data){
                $(".product-characteristics").append(data.result)
            }
        })
    })
    function removeProduct(){
        $(".search-results").css('display', 'block')
        $(".product-search-ajax").css('display', 'block')
        $(".product-characteristic-choices").empty()
        $(".product-characteristic-choices-values").empty()
    }
    function getProduct(productId, title){
        $('.product').append(
            '<div class="alert alert-info alert-dismissible show" id="product-title" role="alert">' + title +
            '<button type="button" onclick="removeProduct()" ' +
            'class="btn-close" data-bs-dismiss="alert" aria-label="Close">' +
            '</button>' +
            '</div>'
        )
        $(".search-results").css('display', 'none')
        $("#search-product-results").empty()
        $(".product-search-ajax").css('display', 'none')
        $(".product-characteristic-choices").css('display', 'block')
        $(".product-characteristic-choices-values").css('display', 'block')
        $('input[name="search-text"]').val("")
        let category_id = $('select[name="category-validators"]').val()
        let data = {
            product_id: productId,
            category_id: category_id
        }
        $.ajax({
            method: "GET",
            data:data,
            dataType: "json",
            url: "/product-specifications/show-all-category-characteristics-ajax/",
            success: function (data){
                $(".product-characteristics").append(data.result)
            }
        })
    }
    $(document).on('change', 'select[name="product-category-characteristics"]', function (){
        let data = {
            category_id: this.value,
            product_characteristic_name: $("#product-category-characteristics-id option:selected").text()
        }
        $.ajax({
            method: "GET",
            dataType: "json",
            data: data,
            url: "/product-specifications/product-characteristic/",
            success: function (data){
                $(".product-characteristic-choices-values").append(data.characteristics)
            }
        })
    })
    $(document).on('change', 'select[name="product-category-characteristics-choices"]', function (){
        $("#create-product-characteristic").css('display', 'block')
    })
    $('select[name="category-validators"]').on('change', function() {
    $(".product").empty()
    $(".errors").empty()
    $("#search-product-results").empty()
    $(".product-search-ajax").css('display', 'block')
    });
    $('input[name="search-text"]').on('input', function(){
    if(this.value.length == 0){
        $(".search-results").css('display', 'none')
    }else{
        $(".search-results").css('display', 'block')
    }
    $("#search-product-results").empty()
    let data = {
        query: this.value,
        category_id: $('select[name="category-validators"] option').filter(':selected').val()
    }

    $.ajax({
    method: "GET",
    dataType: "json",
    data: data,
    url: "/product-specifications/search-product/",
    success: function(data){
        let items = []
        if(data.result.length < 1){
            $('#no-results').css('display', 'block')
        }else{
            $('#no-results').css('display', 'none')
        }
        $.each(data, function (index, value) {
            $.each(value, function (idx, v){
                if($.inArray(v, items) == -1){
                    items.push(v)
                    $('#search-product-results').append(
                        '<li class="list-group-item list-group-item-action" ' +
                        'onclick="getProduct(\'' + v.id + '\', \'' + v.title + '\')" ' +
                        'style="cursor: pointer" id="product-' +
                        v.id + '">'
                        + v.title +
                        ' | ' +
                        v.price +
                        ' руб.' +
                        '</li>')
                        }
                    })
                })
            }
        })
    })
</script>
{% endblock js %}

shop/specifications/templates/new_category.html
{% extends 'product_characteristics.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-12">
        <form action="{% url 'new-category' %}" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
        <input type="submit" class="btn btn-success" value="Создать">
        </form>
    </div>
{% endblock %}

shop/specifications/templates/new_characteristic.html
{% extends 'product_characteristics.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form action="{% url 'new-characteristic' %}" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
<input type="submit" class="btn btn-success" value="Создать">
</form>
{% endblock %}

shop/specifications/templates/new_validator.html
{% extends 'product_characteristics.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="category-validator-div">
    <label for="category-validators-id">Категория</label>
    <select class="form-select" required name="category-validators" id="category-validators-id" aria-label="Default select example">
    <option selected>---</option>
        {% for category in categories %}
          <option value="{{ category.id }}">{{ category.name }}</option>
        {% endfor %}
    </select>
</div>
<div class="characteristic-validator-div" style="display: None; padding-top: 20px;">
</div>
<div class="characteristic-value-div" style="padding-top: 20px;">

</div>
<div class="errors">

</div>
{% endblock %}

shop/specifications/templates/product_characteristics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>Title</title>
</head>
<style>
    #id_characteristic {
        width: 200px;
        margin-right: 15px;
    }
    #id_characteristic_key_name {
        width: 400px;
        margin-right: 15px;
    }
</style>
<body>
<div class="container">
<h3 class="text-center">Админка характеристик</h3>
<hr>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}
<div class="row">
    <div class="col-md-4">
<div class="list-group">
    <a href="{% url 'new-category' %}" class="list-group-item list-group-item-action {% if request.path == "/product-specifications/new-category/" %}active{% endif %}" aria-current="true">
    Создать новую категорию
  </a>
  <a href="{% url 'new-characteristic' %}" class="list-group-item list-group-item-action {% if request.path == "/product-specifications/new-characteristic/" %}active{% endif %}" aria-current="true">
    Создать новую характеристику
  </a>
    <a href="{% url 'new-validator' %}" class="list-group-item list-group-item-action {% if request.path == "/product-specifications/new-validator/" %}active{% endif %}" aria-current="true">
    Создать значение характеристики
  </a>
    <a href="{% url 'new-product-characteristic' %}" class="list-group-item list-group-item-action {% if request.path == "/product-specifications/new-product-characteristic/" %}active{% endif %}" aria-current="true">
    Создать характеристику для товара
    <a href="{% url 'update-product-characteristics' %}" class="list-group-item list-group-item-action {% if request.path == "/product-specifications/update-product-characteristics/" %}active{% endif %}" aria-current="true">
    Редактировать характеристику для товара
  </a>
</div>
    </div>
    <div class="col-md-8">
    {% block content %}
    {% endblock %}

    </div>
</div>
{% block productcharacteristicsupdate %}
{% endblock productcharacteristicsupdate %}
{% block masscharacteristics %}
{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
{% block js %}
<script>
        $('select[name="category-validators"]').on('change', function() {
        var categoryId = this.value;
        data = {
            category_id: categoryId
        }
        prev_choice = categoryId
        $(".characteristic-validator-div").empty()
        $(".characteristic-value-div").empty()
        $(".errors").empty()
        $.ajax({
            method: "GET",
            dataType: "json",
            data: data,
            url: "/product-specifications/characteristic-choice/",
            success: function(data){
                $(".characteristic-validator-div").css('display', 'block');
                $(".characteristic-validator-div").append(data['result'])
            }
        })
    });
    $(document).on('change', 'select[name="characteristic-validators"]', function(){
        $('.characteristic-value-div').empty()
        $('.errors').empty()
        $('.characteristic-value-div').append(
            '<input type="text" class="form-control" id="characteristic-value" required></input>',
            '<br>',
            '<input type="submit" class="btn btn-success" id="create-validator" value="Создать">'
        )
    })
</script>
<script>
    $(document).on('click', '#create-validator', function (){
        var catgoryId = $("#category-validators-id").val();
        var characteristicName = $("#characteristic-validators-id").val();
        var characteristicValue = $("#characteristic-value").val()
        data = {
            category_id: catgoryId,
            characteristic_name: characteristicName,
            characteristic_value: characteristicValue
        }
        $.ajax({
            method: "GET",
            dataType: "json",
            data:data,
            url: "/product-specifications/characteristic-create/",
            success: function (data){
                if('error' in data){
                    $('.errors').append(
                        '<p class="text-center" style="color:red;"><strong>' + data['error'] + '</strong></p>'
                    )
                }else{
                    console.log('asdasdasdasdasd')
                    window.location.href="/product-specifications/"
                }
            }
        })
    })
</script>
{% endblock js %}
</body>
</html>